### ISSUE TITLE
Add top tagging of large R jets based only on mass

### ISSUE THREAD

**Issue by AvivCukierman** [kratsg/TheAccountant#106]
The branches can be named like "topTag_JustMass_jet_largeR_%i"

**Comment by AvivCukierman** [comment]
And also the multiplicities for the optimization

**Comment by mattleblanc** [comment]
We could also consider optimising while including the mass of the leading 4-5 large-R jets and none of the current top-tagging branches (rather than a bool for whether each jet passes the mass requirement or not). This would avoid the need to pick just one cut value off the top ... if there is an optimal value, the optimisation should show this to us anyway.

**Comment by AvivCukierman** [comment]
@mattleblanc optimization currently does not support cutting on mass windows (though that would be easy to implement). More importantly, and harder to implement, optimization currently does not support counting the number of jets that pass a mass window cut, if it wasn't done in TA. I'll file an issue in optimization though.

**Comment by mattleblanc** [comment]
True. A minimum mass cut may suffice, though.

Otherwise, how are we considering which mass window to apply? I'd suggest looking at two: one which includes the W peak, and one which excludes it ...

**Comment by AvivCukierman** [comment]
I think the top tagging definitions are from here: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/TopTaggingPreRecommendations2015
We're not optimizing on it yet.
If the issues I just filed get added to optimize, then we could have more freedom on the top tagging.

**Comment by mswiatlo** [comment]
(Just noting that the current run on the data/mc, tag_08, is using slightly older top-tagging recommendations, but mostly compatible with this twiki. I have updated to the latest recommendations, but this isn’t committed yet. Next run will have the very-latest everything.)

On Aug 24, 2015, at 11:13 AM, AvivCukierman <notifications@github.com<mailto:notifications@github.com>> wrote:

I think the top tagging definitions are from here: https://twiki.cern.ch/twiki/bin/view/AtlasProtected/TopTaggingPreRecommendations2015
We're not optimizing on it yet.
If the issues I just filed get added to optimize, then we could have more freedom on the top tagging.

**Comment by mswiatlo** [comment]
Sorry, reading this over again I see my previous comment was not very relevant.

So yes, right now it's a bit tricky to say something like "optimize the number of jet which pass a mass cut." You can, however, just enter the leading/second/third/fourth jet masses into the optimization, and see what the optimal cut is for each. If they're approximately consistent (i.e., > 150 for leading subleading and leading, >50 for third leading) then that tells us something already. It's a bit less automatic, but we should still pursue this.

**Comment by kratsg** [comment]
@mattleblanc Optimization now supports the mass window functionality.

**Comment by kratsg** [comment]
I'm closing this. We're able to support custom mass-taggers in the optimization code.
