### ISSUE TITLE
Meff distribution

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#11]

**Comment by kratsg** [comment]
Effective mass is defined as the scalar sum of the transverse momenta of the leading `N` jets in the event together with MET:

![latexit-drag](https://cloud.githubusercontent.com/assets/761483/7232236/1498c318-e740-11e4-8310-a8add00c378e.png)

**Comment by fizisist** [comment]
That's correct.

**Comment by kratsg** [comment]
We'll use [`xAOD::MissingET::met()`](http://acode-browser.usatlas.bnl.gov/lxr/source/atlas/Event/xAOD/xAODMissingET/xAODMissingET/versions/MissingET_v1.h#0037)

> ```
> 0037     double met()   const; /*!< @brief Returns @f$ E_{\rm T}^{\rm miss} = \sqrt{(p_{x}^{\rm miss})^{2} + (p_{y}^{\rm miss})^{2}} @f$ */
> ```

**Comment by fizisist** [comment]
Shouldn't we use the MET from SUSYTools?

**Comment by mswiatlo** [comment]
This is complicated right now, since the MBJ code (which implements SUSYTools) doesn’t output xAOD’s properly yet.

So, to run on xAOD’s ourselves in the short term, we either implement SUSYTools ourselves, or just do the “right” thing.
In the long term (though really, this should be started soon), we should get the MBJ code outputting nice, decorated, minimal xAODs— and then we can turn off this part of the code dynamically, since the MET will be defined by the reduced xAOD.

This is the path I suggested to Giordon, but was hoping we could discuss it tomorrow (or anytime) with you as well.

On Apr 21, 2015, at 7:01 PM, David Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

Shouldn't we use the MET from SUSYTools?

**Comment by kratsg** [comment]
I tried to align as close with `SUSYTools` as possible. The only difference is that our MET that we grab is un-rebuilt. Do we want to add add `SUSYTools` as a dependency (it's a really big package and has a lot of dependencies and is unfortunately annoying to compile).

``` c++
    declareProperty( "METElectronTerm", m_eleTerm    = "RefEle"           ) ;
    declareProperty( "METGammaTerm", m_gammaTerm  = "RefGamma"         ) ;
    declareProperty( "METTauTerm", m_tauTerm    = "RefTau"            )  ;
    declareProperty( "METJetTerm", m_jetTerm    = "RefJet"            ) ;
    declareProperty( "METMuonTerm", m_muonTerm   = "Muons"             ) ;
    declareProperty( "METInputMap", m_inputMap   = "METMap_RefFinal"   ) ;
    declareProperty( "METInputCont", m_inputMETCont = "MET_RefFinal"   ) ;
    declareProperty( "METOutputTerm", m_outMETTerm   = "Final"             ) ;
```

``` c++
  StatusCode SUSYObjDef_xAOD::GetMET(xAOD::MissingETContainer &met,
                     const xAOD::JetContainer* jet, 
                     const xAOD::ElectronContainer* elec,
                     const xAOD::MuonContainer* muon,
                     const xAOD::PhotonContainer* gamma,
                     const xAOD::TauJetContainer* taujet,
                     bool doTST) {

    const xAOD::MissingETContainer* metcontainer = 0; 
    if( evtStore()->retrieve( metcontainer, m_inputMETCont ).isFailure() ) {
      ATH_MSG_WARNING( "MET container could not be retrieved" );
    }    

    if (!metcontainer) {
      ATH_MSG_ERROR( "Failed to retrieve MET container" );
      return StatusCode::FAILURE; // fixme
    }    

    xAOD::MissingETContainer::const_iterator met_it = metcontainer->find("Final");

    if (met_it == metcontainer->end()) {
      ATH_MSG_ERROR( "No RefFinal inside MET container" );
    }    

    double mpx = (*met_it)->mpx();
    double mpy = (*met_it)->mpy();

    ATH_MSG_INFO( "Un-rebuilt MET: Missing Et (x,y): (" << mpx << "," <<  mpy << ")");

    const xAOD::MissingETComponentMap* metMap = 0; 
    if( evtStore()->retrieve(metMap, m_inputMap).isFailure() ) {
      ATH_MSG_WARNING("Unable to retrieve MissingETComponentMap: " << m_inputMap);
      return StatusCode::SUCCESS;
    }    

    bool doTracks = false;
    bool doJVFCut = false;
    bool pureTrkSoft = false;
    std::string softTerm = "SoftClus";
    std::string softJetScale = "JetConstitScaleMomentum";
    if(doTST) {
      doTracks = true;
      pureTrkSoft = true;
      doJVFCut = true;
      softTerm = "PVSoftTrk";
      softJetScale = "JetTrackScale";
    }

    ATH_MSG_DEBUG("Build MET with tracks? " << doTracks);

    if(m_doEle) {
      ATH_MSG_VERBOSE("Build electron MET");
      if(elec) {
    ATH_CHECK( m_metRebuilder->rebuildMET(m_eleTerm, &met, elec, metMap, doTracks) );
      } else {
    ATH_CHECK( m_metRebuilder->copyMET(m_eleTerm,&met,metMap) );
      }
    }

    if(m_doGamma) {
      ATH_MSG_VERBOSE("Build photon MET");
      if(gamma) {
    ATH_CHECK( m_metRebuilder->rebuildMET(m_gammaTerm, &met, gamma, metMap, doTracks) );
      } else {
    ATH_CHECK( m_metRebuilder->copyMET(m_gammaTerm,&met,metMap) );
      }
    }

    if(m_doTau) {
      ATH_MSG_VERBOSE("Build tau MET");
      if(taujet) {
    ATH_CHECK( m_metRebuilder->rebuildMET(m_tauTerm, &met, taujet, metMap, doTracks) );
      } else {
    ATH_CHECK( m_metRebuilder->copyMET(m_tauTerm,&met,metMap) );
      }
    }

    if(m_doMuon) {
      ATH_MSG_VERBOSE("Build muon MET");
      if(muon) {
    ConstDataVector<xAOD::MuonContainer> metmuon(SG::VIEW_ELEMENTS);
    for(const auto& mu : *muon) {
      if(mu->muonType()==xAOD::Muon::Combined || mu->muonType()==xAOD::Muon::SegmentTagged || mu->muonType()==xAOD::Muon::MuonStandAlone)
        metmuon.push_back(mu);
    }
    ATH_CHECK( m_metRebuilder->rebuildMET(m_muonTerm, &met, metmuon.asDataVector(), metMap, doTracks) );
      } else {
    ATH_CHECK( m_metRebuilder->copyMET(m_muonTerm,&met,metMap) );
      }
    }

    if(!jet) {
      ATH_MSG_WARNING("Invalid jet container specified for MET rebuilding!");
      return StatusCode::SUCCESS;
    }
    ATH_MSG_VERBOSE("Build jet/soft MET");
    ATH_CHECK( m_metRebuilder->rebuildJetMET(m_jetTerm, softTerm, &met, jet, metMap,
                         doTracks, doJVFCut, pureTrkSoft, softJetScale) );

    ATH_MSG_VERBOSE("Apply MET systematics");
    if( m_metSystTool->applyCorrection(*met[softTerm]) != CP::CorrectionCode::Ok ) {
      ATH_MSG_WARNING("GetMET: Failed to apply MET soft term systematics.");
    }

    ATH_MSG_VERBOSE("Build MET sum");
    ATH_CHECK( m_metRebuilder->buildMETSum(m_outMETTerm, &met) );
    ATH_MSG_INFO( "Done rebuilding MET." );

    double rebuilt_mpx = met["Final"]->mpx();
    double rebuilt_mpy = met["Final"]->mpy();

    ATH_MSG_INFO( "Rebuilt MET: Missing Et (x,y): (" << rebuilt_mpx << "," <<  rebuilt_mpy << ")");

    return StatusCode::SUCCESS;

  }
```

**Comment by fizisist** [comment]
Ok, I think I understand (well, not why the plan that I thought was in place to made DxAODs didn't come to fruition, but that's another story)

**Comment by kratsg** [comment]
A solution is to temporarily add `SUSYTools` so we can throw these special objects, like the re-built MET back into the TStore so that I can pick it up downstream in the rest of the code (which is configurable for exactly this reason).

**Comment by mswiatlo** [comment]
I feel like the _right_ thing to do is to get the MBJ code outputting nice, normalized xAODs that we can use without the overhead of SUSYTools. Anything we run over DxAOD or xAOD ourselves is going to be a temporary solution, and good for early R&D, but probably not for final results. Up to you on how you want to handle that though, Giordon.

On Apr 21, 2015, at 7:16 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

A solution is to temporarily add SUSYTools so we can throw these special objects, like the re-built MET back into the TStore so that I can pick it up downstream in the rest of the code (which is configurable for exactly this reason).

**Comment by kratsg** [comment]
I'll close this and refer to #17 for discussions like this about the output from MBJ. This issue was closed since we have Meff distributions incorporated properly.
