### ISSUE TITLE
MET delta-phi selection

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#13]

**Comment by kratsg** [comment]
If MET is too aligned with a jet, it represents more of the energy imbalance due to the jet reconstruction.

**Comment by kratsg** [comment]
This doesn't quite belong in the milestone.

**Comment by kratsg** [comment]
How about we only select on something like

![latexit-drag](https://cloud.githubusercontent.com/assets/761483/7286106/f7e92584-e90e-11e4-8313-acc7bc350628.png)

``` latex
(\Delta\phi)_\text{MET} = \min( \left|\phi_{\text{MET}} - \phi_{\text{jet}}^i \right| )
```

**Comment by mswiatlo** [comment]
Is this implemented? Each FinalSignalJet needs the further than 0.4 in DeltaR from the direction of the MET.

**Comment by kratsg** [comment]
This isn't implemented yet. I'll have to add it to the `VariableDefinitions`

**Comment by mswiatlo** [comment]
Not a big deal yet, but this is a traditional part of the pre-selection.

**Comment by kratsg** [comment]
Do we veto events that do not pass this cut? I'm guessing "yes".

**Comment by mswiatlo** [comment]
Yup.
