### ISSUE TITLE
lepton pT and isolations

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#14]
For veto in the case of the 0-lepton analysis
- [x] lepton veto
- [ ] pt isolation

**Comment by kratsg** [comment]
@mswiatlo will figure out which cone SUSYTools does. We'll need to implement isolation ourselves... and probably OverlapRemover using `xAODAnaHelpers` for this. Hopefully it should work for right now.

**Comment by mswiatlo** [comment]
Bumping this. #30 is related. But to really do 0-lepton optimization, we need the lepton veto.

**Comment by mswiatlo** [comment]
I"ll get more info on the way SUSYTools does this, in case we want to do it "quickly" ourselves.

**Comment by mswiatlo** [comment]
Looks the right way way to check for this is using the `overlaps` decoration (a char) on muons/electrons. Veto if `overlaps` == 1.

The isolation is probably this:

`Float_t ptvarcone20 = 0;
electron->isolationValue(ptvarcone20,xAOD::Iso::ptvarcone20);`

but I'm not 100% sure. It could be on the `ptvarcone30` variable instead. The cut is at < 0.05. I wouldn't worry about isolation yet; we'll get a response from Antoine/JF soon hopefully.

But be sure to remove leptons that do not pass the overlap, as described above.

**Comment by kratsg** [comment]
Is the `overlaps` decoration on the leptons set to `true` if it overlaps with a jet and `false` if it doesn't? Or passing the OverlapRemoval from SUSYTools using a various set of selections?

So I should do something like:

``` c++
static SG::AuxElement::ConstAccessor isOverlap("overlaps");
if(!isOverlap.isAvailable(*el) || !isOverlap.isAvailable(*mu)) return EL::StatusCode::FAILURE;
if(isOverlap(*el) || isOverlap(*mu)) wk()->skipEvent();
```

or should I make a new container that only contains leptons that do not overlap with jets?

**Comment by mswiatlo** [comment]
> or should I make a new container that only contains leptons that do not overlap with jets?

This, basically. 

I imagine eventually we'll put this cut into the mainline code, but for now this additional cleaning is necessary.

**Comment by kratsg** [comment]
For lepton veto, I wrote a templated function that basically creates a view. Here's how you use it:

```
  if(!m_inputElectrons.empty())
    ConstDataVector<xAOD::ElectronContainer> VetoElectrons(VD::leptonVeto(in_electrons));
  if(!m_inputMuons.empty())
    ConstDataVector<xAOD::MuonContainer> VetoMuons(VD::leptonVeto(in_muons));
```

Here's the templated function

```
  // build lepton veto using overlaps
  template <typename T>
  ConstDataVector<T> leptonVeto(const T* leptons, std::string d_overlap = "overlaps"){
    ConstDataVector<T> VetoLeptons(SG::VIEW_ELEMENTS);
    SG::AuxElement::ConstAccessor<int> isOverlap(d_overlap);
    for(auto l: *leptons){
      if(!isOverlap.isAvailable(*l) || isOverlap(*l) == 1) continue;
      VetoLeptons.push_back(l);
    }
    return VetoLeptons;
  }
```

which is relatively easy to use. It's not clear how to use the lepton veto RIGHT now so I'm putting the functionality in and will chat tomorrow to tie up this end.

**Comment by kratsg** [comment]
FYI, Lepton veto was implemented. All that's left is pT isolation.

**Comment by kratsg** [comment]
@mswiatlo isolation would be great to have, is that the decoration `signal_pt_isolation_req` or something that I see in MBJ?
