### ISSUE TITLE
Increase domain on subjettiness plots

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#31]
https://github.com/kratsg/TheAccountant/blob/master/Root/JetHists.cxx#L28-L29

Should go up to like 1.5 and not 1.0.

**Comment by mswiatlo** [comment]
rly? I thought 1 was the maximum by construction.

On May 6, 2015, at 5:40 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

https://github.com/kratsg/TheAccountant/blob/master/Root/JetHists.cxx#L28-L29

Should go up to like 1.5 and not 1.0.

**Comment by kratsg** [comment]
The plots show it cuts off a bit too low.
