### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#33]
For jets that pass the pre-selection (standard: >= 4 jets with pT > 30 GeV and >= 2 of them b-tagged).
- [x] effective mass
- [x] total pt
- [x] total transverse mass
- [x] number of jets
- [x] number of bjets
- [x] number of large-R jets
- [x] loose top tag (large-R jet)
- [x] medium top tag (large-R jet)
- [x] tight top tag (large-R jet)
- [ ] medium W tag (large-R jet)
- [ ] tight W tag (large-R jet)
- [x] reclustered R (0.8, 1.0, 1.2)
  - [x] pt (leading 4 rc jets)
  - [x] mass (leading 4 rc jets)
  - [x] split12 (leading 4 rc jets)
  - [x] split23 (leading 4 rc jets)
  - [x] nsubjets (leading 4 rc jets)

`11 + 3*(4*5) = 71 branches`

**Comment by mswiatlo** [comment]
It'd also be good to focus, perhaps at first, at normal top-tagging comparisons to various re-clustered parameters.

**Comment by kratsg** [comment]
@mswiatlo - What specific variables do we want to look at?

Reclustering is not a part of `TheAccountant` yet. I can add it in the algorithm chain so the jets are available for us to use. But for right now, I just want to keep it out since it tends to be one of those things I should be getting from MBJ.

**Comment by kratsg** [comment]
Also, what kind of configurability do we want here? I think I'm just going to hardcode the branches involved and changes will just break backwards compatibility usually.

**Comment by mswiatlo** [comment]
With the normal top tags, there's just two variables basically: number of medium tags and number of loose tags.

With re-clustering, we have more options, basically on how to define "tag." The re-clustering can be done with several different R's, and then the tag can be done with several different mass windows, and subsequent cuts on the splitting scales. To start, it'd probably be good to come up with ~15 configurations which scan the space of available "tag" definitions. So something like

R size: 0.8, 1.0, 1.2
mass window: 10 GeV around 175, 20 GeV around 175
split12: no cut, loose cut
split23: no cut, loose cut

This is 24 definitions of a tag. We can dump "number of re-clustered jets which pass TagXX" as a variable into your optimization n-tuple. Then we see what the best one is, and compare to the "normal" top tag. 

There might be a follow-up step (likely there will be) when we zoom in and do another step of optimization around one of the first configurations you found through this.

(Alternatively: you can just dump the re-clustered R, mass, and split12/split23 for the leading 3-4 reclustered jets. That's 16 floats per R size. You can then do the optimization completely off-line, on the small n-tuple, to find the best cuts.)

**Comment by mswiatlo** [comment]
I'm fine with hard-coding, definitely. #GetThingsDone

**Comment by mswiatlo** [comment]
Thinking on it a bit more, I like the idea of storing the floats-- pt/mass/split12/split23-- for each of the leading 4 re-clustered jets in the analysis, for several R sizes. Then do the optimization off-line. Requires less laborious re-running, and gives more flexibility on the optimal cuts at the end.

**Comment by mswiatlo** [comment]
Sorry for the disorganized replies: one more thought on hard-coding. Be sure to keep things flexible enough that in the future, we can do a similar procedure for the jigsaw optimization without too many changes (just adding more member variables for the pointers to dump, etc.).

**Comment by kratsg** [comment]
https://cds.cern.ch/record/2011623

Look in 6.4.1 for the 1-lepton studies.

**Comment by kratsg** [comment]
![screenshot 2015-05-19 11 55 44](https://cloud.githubusercontent.com/assets/761483/7708818/0a8f2c8c-fe1e-11e4-8fe3-f2ca56973e43.png)
![screenshot 2015-05-19 11 55 50](https://cloud.githubusercontent.com/assets/761483/7708819/0a93b694-fe1e-11e4-8c33-ab5e57409c7c.png)

**Comment by kratsg** [comment]
See https://svnweb.cern.ch/trac/atlasphys-susy/browser/Physics/SUSY/Analyses/MultiBJets/MultibjetsAnalysis/trunk/Root/Variables.cxx for how the Multibjets does it.

**Comment by mswiatlo** [comment]
Dunno if this is closed-- we really need the re-clustering comparisons. The tagging with those variables is really the thing that we have the most room on optimizing, so it'll be important to compare.

Basically, dumping the pt/mass/split12/split23/nsubjets for the leading 4 jets, would be very helpful.

**Comment by kratsg** [comment]
You have more experience with the TTree and Branches. Should I be creating a branch of the leading 4 jet pt as a `vector<float>` [not sure how?] or just create 4 new branches for just that?

It's probably easier to keep the ntuple as flat as possible? Not sure. I would be ok either way since I'll be writing a majority of the auto-optimizing code in python+numpy and I'm highly skilled in that.

**Comment by mswiatlo** [comment]
My preference is to keep it completely flat, so no vectors, just named branches that correspond to the jet number.

Though this is just a preference; as you say, either way will work.

On May 23, 2015, at 11:15 AM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

You have more experience with the TTree and Branches. Should I be creating a branch of the leading 4 jet pt as a vector<float> [not sure how?] or just create 4 new branches for just that?

It's probably easier to keep the ntuple as flat as possible? Not sure. I would be ok either way since I'll be writing a majority of the auto-optimizing code in python+numpy and I'm highly skilled in that.

##

**Comment by kratsg** [comment]
Awesome. Can I clarify the jet definitions for the various ntuples being dumped?
- jets (AntiKt10LCTopoJets / Akt10TrimmedJets / Calibrated from SUSYTools)
- b-jets (AntiKt4LCTopoJets / Akt4TrimmedJets / Calibrated from SUSYTools)
- reclustered jets (reclustered from small-R jets, probably the b-jets being used)

On top of that, reclustering has various definitions. So here's what I have currently.

The following use MET, 0-Leptons, and Akt4LCTopoJets / Akt10LCTopoJets (not trimmed). _should probably switch to trimmed jets from now on_
- effective mass
- total pt
- total transverse mass
- number of b-jets
- number of jets
- loose top tag (jet)
- medium top tag (jet)
- tight top tag (jet)

The following will be dumped for reclustered-trimmed jets (for a given "standard trimming of 5%"): _should we not look at variable-R reclustering for right now, and just use standard reclustering?_
- pt (leading 4 jets)
- mass (leading 4 jets)
- split12 (leading 4 jets)
- split23 (leading 4 jets)
- nsubjets (leading 4 jets)
- reclustered R

Of all of this, we need an event pre-selection to be applied to which? Reclustered jets or Akt10LCTopoJets? (it's pretty clear, i think, that the event pre-selection is also applied to b-jets).

**Comment by mswiatlo** [comment]
This all sounds correct. Though the terminology most people use is:
- R=0.4 = small jets, or default jets, or just jets
- R=1.0 trimmed = large jets, trimmed jets

Anyway, everything you have is consistent, so I think we're good.

With regards to VariableR-- skip this for now. We'll need dedicated studies later. But for now, go with R=0.8, 1.0, and 1.2 for the re-clustering. 5% trimming on all of them. The re-clustered R could be part of the jet collections name, and save you an int, if you want.

We discussed the pre-selection; this is done on the R=0.4 jets only.

Nice progress!

**Comment by fizisist** [comment]
I would suggest adding to the optimization 
- jet pT cut (right now it’s 30 GeV, but maybe that’ better at 40 or 50 or 25?)
- Nbjet

**Comment by kratsg** [comment]
@fizisist 's pre-selections recommendations will be implemented as separate jobs to keep things modular. I need to update Preselect to correctly apply the jet pT cut as well as definition for Nbjet. It currently does not do this.

**Comment by kratsg** [comment]
Here are our supported arguments for preselections + optimizations to `CookTheBooks.py`
- require 4 jets with pT > 30 GeV
  - require 2 of those jets to be b-tagged (bjets) using some cut on MV1 (figure out working points by for Multi-B-Jets)
- dump the optimization ntuple (eg: run the algorithm)

```
--jet_minNum=4
--jet_minPt=30
--jet_MV1=0.7
--bjet_minNum=2
--optimizationDump
```

The following arguments are used for now as placeholders for features that need to be implemented later in the plotting code (`Report.cxx`):

```
--passPreSel
--numLeadingJets=4
--decorJetTagsTop=
--decorJetTagsW=
--decorJetTagsB=
```

An example of a run I did just for testing on 10 events:

```
CookTheBooks.py /share/t3data3/kratsg/xAODs/mc14_13TeV.110351.PowhegPythia_P2012_ttbar_allhad.merge.DAOD_JETM8.e3232_s1982_s2008_r5787_r5853_p1862_tid05115801_00/DAOD_JETM8.05115801._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.110401.PowhegPythia_P2012_ttbar_nonallhad.merge.DAOD_SUSY4.e2928_s1982_s2008_r5787_r5853_p1862_tid05130501_00/DAOD_SUSY4.05130501._000021.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204533.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1000_T5000_L100.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604181_00/AOD.01604181._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204534.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1300_T5000_L100.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604182_00/AOD.01604182._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204535.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1600_T5000_L100.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604183_00/AOD.01604183._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204536.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1900_T5000_L100.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604184_00/AOD.01604184._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204537.Herwigpp_UEEE4_CTEQ6L1_Gtt_G2200_T5000_L100.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604185_00/AOD.01604185._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204539.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1300_T5000_L400.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604187_00/AOD.01604187._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204540.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1300_T5000_L700.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604188_00/AOD.01604188._000001.pool.root.1 /share/t3data3/kratsg/xAODs/mc14_13TeV.204541.Herwigpp_UEEE4_CTEQ6L1_Gtt_G1300_T5000_L900.merge.AOD.e3094_s1982_s2008_r5787_r5853_tid01604189_00/AOD.01604189._000001.pool.root.3 -v -f --jet_minNum=4 --jet_minPt=30 --jet_MV1=0.7 --bjet_minNum=2 --passPreSel --numLeadingJets=4 --decorJetTagsTop= --decorJetTagsW= --decorJetTagsB= --optimizationDump --nevents=10
```

**Comment by kratsg** [comment]
I've updated to add 'W' tags to the list. This is currently not implemented just yet. One reason is that I would like to wait for Miles to verify that he can tag BosonTag v2.0 in JSSU first so that we have it in AB releases. 

The other reason is that it still needs more studying, I think. For more information, see https://github.com/kratsg/JetSubstructureTools/wiki/BosonTag

**Comment by kratsg** [comment]
We will want to produce something like the table on slide 5 : https://indico.cern.ch/event/393585/session/0/contribution/2/material/slides/0.pdf for the optimization.

**Comment by kratsg** [comment]
The main thing to finish off the set of optimizations is to get the correct weights in place. Since it's been somewhat decided to unequivocally set event weights to one for all files (data and mc) - each file will be scaled downstream in https://github.com/kratsg/Optimization and https://github.com/kratsg/TakeOverTheWorld. See https://github.com/kratsg/TakeOverTheWorld/blob/master/weights.yml for an example file that will be filled in.

**Comment by kratsg** [comment]
Apart from W-tags which @nharrison314 works on. I think I'm going to close this issue for now since we've satisfied the standard optimizations for the first run through of the analysis.
