### ISSUE TITLE
top tags

### ISSUE THREAD

**Issue by mswiatlo** [kratsg/TheAccountant#56]
`btw— plz plot # of top tags in the event for largeR jets`

**Comment by mswiatlo** [comment]
(you can do the tag value for the leading 4, and then the number of jets with a tag, for the combined view)

**Comment by mswiatlo** [comment]
this should be done for all 4 taggers: smoothTight, smoothLoose, loose, tight

**Comment by kratsg** [comment]
This is currently in a broken state until @mswiatlo produces new mini-xAODs. The problem is summarized here https://github.com/kratsg/xAODDumper/issues/16

**Comment by kratsg** [comment]
![screenshot 2015-06-19 22 08 21](https://cloud.githubusercontent.com/assets/761483/8265781/b8984b00-16cf-11e5-9b1e-c6c28023fe85.png)

This is ready to work when we flip the switch in `JetTagHists.cxx`.
