### ISSUE TITLE
configurable thresholds for largeR jet

### ISSUE THREAD

**Issue by mswiatlo** [kratsg/TheAccountant#58]
Right now, I think the way thresholds are implemented are such that if they exist, we require `--jetLargeR_minNum` with pT > `--jetLargeR_minPt`. This is handy, but another nice option would be "only consider largeR jets with pT > `--jetLargeR_minViewPt`: this way, we can just say "ignore all the junk with less than 300 GeV and only plot stuff higher than that."

**Comment by kratsg** [comment]
![screenshot 2015-06-19 23 46 07](https://cloud.githubusercontent.com/assets/761483/8266042/7054018c-16dd-11e5-9b91-3e58b492e445.png)

```
CookTheBooks.py /share/t3data3/kratsg/xAODs/user.mswiatlo.00266904.physics_Main.f594_m1435_p2361_11_output_xAOD.root/*.root
-v -f --jet_minNum=4 --jet_minPt=30 --bjet_minNum=2 --numLeadingJets=4
--decorJetTagsTop= --decorJetTagsW= --decorJetTagsB=
--optimizationDump --jetsLargeR=FinalFatJets --jets=FinalSignalJets
--met=Mettst --eventInfo=BaseEventInfo --mode=branch --jetLargeR_minPtView=300
```

this was run over at least 10,000 events. Not bad.
