### ISSUE TITLE
Implement the standard pre-selection

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#6]
- [x] 4 jets with pT>30GeV
- [x] 2 b-jets with pT>30GeV

**Comment by kratsg** [comment]
To implement the standard pre-selection, one would run:

```
CookTheBooks.py ../xAODAnalysis/input.root -f \
--jets="AntiKt10LCTopoJets" \
--jet_minNum=3 --jet_minPt=30 \
--bJets="AntiKt4LCTopoJets" \
--bjet_minNum=1 --bjet_minPt=30 \
--passPreSel
```

Note that by default, I will always use exclusive cuts to keep things consistent and simple (besides, `>=` looks uglier than just `>`)

**Comment by fizisist** [comment]
This comment only applies to the `pT` cuts, correct? I would advocate that 

```
--jet_minNum=3
```

means `>=3 jets`

**Comment by kratsg** [comment]
After sleeping on it, I think that makes more sense. Would you also want something like

```
--jet_minPt=30
```

to mean `jet.pT >= 30 GeV`?

**Comment by fizisist** [comment]
So are the selections `>=` or `=`? I think it's less important for the pT selections, but as I said before, something like 

```
--jet_minNum=3
```

should definitely mean `>=3`

**Comment by kratsg** [comment]
That's currently set in now: 

https://github.com/kratsg/TheAccountant/blob/7679a890a18895961f67dfd12bb29ed23dfabb51/Root/Preselect.cxx#L101-L102

``` c++
  if(num_passJets < m_jet_minNum) return EL::StatusCode::SUCCESS;
  if(num_passJets > m_jet_maxNum) return EL::StatusCode::SUCCESS;
```

https://github.com/kratsg/TheAccountant/blob/7679a890a18895961f67dfd12bb29ed23dfabb51/Root/Preselect.cxx#L118-L119

``` c++
  if(num_passBJets < m_bjet_minNum) return EL::StatusCode::SUCCESS;
  if(num_passBJets > m_bjet_maxNum) return EL::StatusCode::SUCCESS;
```

It will only reach the end of the `EL::Algorithm::execute()` call if `m_jet_minNum <= num_passJets <= m_jet_maxNum` and `m_bjet_minNum <= num_passBJets <= m_bjet_maxNum` (and hence passes the pre-selection).
