### ISSUE TITLE
Incompatible EventInfo objects!

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#63]
All of the files in `_12_output_xAOD` have compatible `EventInfo` objects that I can dump information about.

All of the files in `_14_output_xAOD` do not have compatible `EventInfo` objects (missing everything).

What are the differences between these that would cause this issue? Can we get `_14` re-run at all?

**Comment by mswiatlo** [comment]
Only difference was the EventLoopGrid tag. I can debug this tomorrow.

On Jun 25, 2015, at 7:52 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

All of the files in _12_output_xAOD have compatible EventInfo objects that I can dump information about.

All of the files in _14_output_xAOD do not have compatible EventInfo objects (missing everything).

What are the differences between these that would cause this issue? Can we get _14 re-run at all?

##

**Comment by kratsg** [comment]
`_17` also has this problem. The `EventInfo` is blank (I can't grab eventNumber or runNumber or lumiBlock for example).

It may not be copied correctly.

**Comment by kratsg** [comment]
As a monkey-patch solution,

I will skip the check if it is MC. Instead, I will set `weight_mc = 1` internally, and use the `castDouble` code to grab the values and multiply it. Since the SUSY meta file works, the current EventWeight code will look like...

``` c++
float VD::eventWeight(const xAOD::EventInfo* ei, const SH::MetaObject* metaData){
/* COMMENTED OUT FOR NOW MONKEY PATCH
  // is it data?
  static SG::AuxElement::ConstAccessor<uint32_t> eventType("eventTypeBitmask");
  if(!eventType.isAvailable(*ei))
    return 1;
  //if(!ei->eventType( xAOD::EventInfo::IS_SIMULATION ))
  if( !(static_cast<uint32_t>(eventType(*ei)) & xAOD::EventInfo::IS_SIMULATION) )
    return 1;

  static SG::AuxElement::ConstAccessor<float> weight_mc("weight_mc");
  float weight(weight_mc.isAvailable(*ei)?weight_mc(*ei):ei->mcEventWeight());
COMMENTED OUT FOR NOW MONKEY PATCH */

  float weight(1.0);
  float crossSection(1),
        kFactor(1),
        filterEfficiency(1),
  //      xsUncertainty(1),
        numEvents(1);

  // if metadata is set, use it, otherwise pass the event weight, uncorrected
  if(metaData){
    metaData->castDouble(SH::MetaFields::crossSection, crossSection);
    metaData->castDouble(SH::MetaFields::kfactor, kFactor);
    metaData->castDouble(SH::MetaFields::filterEfficiency, filterEfficiency);
    //metaData->castDouble(SH::MetaFields::crossSectionRelUncertainty, xsUncertainty);
    metaData->castDouble(SH::MetaFields::numEvents, numEvents);
  }

  return (weight*crossSection*kFactor*filterEfficiency/numEvents);
}
```

For data, this will set the event weight to 1 (I will double-check with an output). For mc, this should set it appropriately since it's set to 1 otherwise and then scale it based on the susy metadata file factors.

**Comment by mswiatlo** [comment]
This seems to be working fine now, yeah?

**Comment by kratsg** [comment]
I think so. The current solution works great now.
