### ISSUE TITLE
add large R > 300 GeV to pre-selection

### ISSUE THREAD

**Issue by mswiatlo** [kratsg/TheAccountant#67]
Just as a test, let's do a run that requires pT Large > 300 GeV, and require at least one such jet. The data/MC agreement is much better, and there's fewer bumps in the large R distributions. This suggests that such a cut is actually getting us over the trigger thresholds we're running into in the small-jets right now.

**Comment by kratsg** [comment]
```
CookTheBooks.py "/share/t3data3/kratsg/xAODs/_17/*physics_Main*/*.root" \
"/share/t3data3/kratsg/xAODs/_18/*physics_Main*/*.root" \
"/share/t3data3/kratsg/xAODs/_19/*/*.root" \
-v -f \
--jet_minNum=4 --jet_minPt=25 --bjet_minNum=2 --numLeadingJets=4 \
--jetLargeR_minPt=300 --jetLargeR_minNum=1 \
--optimizationDump --jetLargeR_minPtView=300 \
--minMET=50 --mode=branch \
--numLepton=0 -y \
--submitDir=TA03_MBJ17-18-19 > TA03_MBJ17-18-19.log 2>&1 &
```

Running it now.

**Comment by kratsg** [comment]
See documentation here -- this run is labeled `TA03`: https://github.com/kratsg/TheAccountant/wiki/Samples

**Comment by kratsg** [comment]
This is done.
