### ISSUE TITLE
Figure out the issue with subjettiness

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#71]
We see a large peak in the first bin. Should try and cout to figure out what kind of jets are giving this issue (event number + run number).

**Comment by kratsg** [comment]
We still have an issue with subjettiness as of now with the MBJ_tag_10_v1 tag.

**Comment by mswiatlo** [comment]
Issue? Is this on jets we actually care about? If it’s just junk jets outside of acceptance, we shouldn’t care...
