### ISSUE TITLE
Add a cutflow for rejecting at least one bad jet

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#98]
Currently included in the `jets` cutflow, but it should be expanded so that we have clarification over how many events are rejected due to the existence of at least one bad jet

**Comment by kratsg** [comment]
@mswiatlo did you fix this?

**Comment by mswiatlo** [comment]
My cutflow is much improved and happy and easy to compare with Trisha. She and I agree with both 0 and 1L pre-selections, up to the dPhiMETMin cut, and that's being checked soon. This is committed.
